#!/usr/bin/env sh

echo ""
echo "[34m--------------------[39m"
echo "[34mStep 1: npm run lint[39m"
echo "[34m--------------------[39m"

start_time=$(date +%s)

pnpm run lint

end_time=$(date +%s)

elapsed_time=$((end_time - start_time))

echo "[32m√[39m lint check ran successfully! Everything seems ok."

echo ""
echo "[32m√[39m All type were checked. passed."

echo ""
echo "[32mChecked all files in $elapsed_time seconds[39m"

echo ""
echo "[34m----------------------[39m"
echo "[34mStep 2: npm run format[39m"
echo "[34m----------------------[39m"

npm run format

echo ""
echo "[32m√[39m Formatter check passed 100%"

echo ""
echo "[1m  ____                              _  [39m"
echo "[1m / ___| _   _  ___ ___ ___  ___ ___| | [39m"
echo "[1m \___ \| | | |/ __/ __/ _ \/ __/ __| | [39m"
echo "[1m  ___) | |_| | (_| (_|  __/\__ \__ \_| [39m"
echo "[1m |____/ \__,_|\___\___\___||___/___(_) [39m"
echo ""

echo "[32m√ Changes have been commited successfully![39m"
echo ""

# echo "    _    _ _      _              _           ____   _    ____ ____  _____ ____  _   "
# echo "   / \  | | |   _| |_ ___  ___ _| |_ ___    |  _ \ / \  / ___/ ___|| ____|  _ \| |  "
# echo "  / _ \ | | |  |_  __/ _ \/ __|_   _/ __|   | |_) / _ \ \___ \___ \|  _| | | | | |  "
# echo " / ___ \| | |    | ||  __/\__ \ | |_\__ \   |  __/ ___ \ ___) |__) | |___| |_| |_|  "
# echo "/_/   \_\_|_|     \__\___||___/ \___|___/   |_| /_/   \_\____/____/|_____|____/(_)  "
# echo ""